branches:
  only:
    - master
language: node_js
node_js:
  - '6'
os:
  - linux
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
osx_image: xcode7.3
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
install:
  - npm install
after_success:
  - echo 'Done testing install'